version: "3.9"

services:
  api:
    build: . 
    container_name: agentflow_api
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000" 

  bot:
    build: . 
    container_name: agentflow_bot
    command: ["python", "bot.py"]
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    env_file:
      - .env 